### ISSUE TITLE
Support optional matches

### ISSUE THREAD

**Issue by scottlowe** [Swirrl/matcha#11]
I don't know how difficult this would be to implement, and appreciate that it might be an annoying request...

BUT!

It would make the biggest difference to me in my use of Matcha right now.

I note that core.logic has an `:or` match pattern.

**Comment by RickMoynihan** [comment]
Thanks @scottlowe this is pretty high on my wishlist also, I thought I'd created an issue for it already.

I don't think it will be anywhere near impossible to implement, underneath in core.logic it's just a `conde`.

For example this matcha query:

```clojure
(select [?s ?p ?o ?olabel] [[?s ?p ?o] [?o :label ?olabel]])
```

Is really only a little more than macro sugar for this pretty trivial core.logic program:

```clojure
(pldb/with-db db
      (l/run*
        [?s ?p ?o ?olabel]
        (l/fresh
          []
          (triple ?s ?p ?o)
          (triple ?o :label ?olabel))))
```

`OPTIONAL`s in `SPARQL` are essentially a binary operator with a LHS and a RHS. i.e. `{ ,,, } OPTIONAL { ,,,stuff,,, }`; though SPARQL has some sugar that adds the LHS brackets for you - meaning it's left associative.  The main task would be to come up with a matcha syntax for this that we like e.g. maybe something like this:

```clojure
(select [?s ?p ?o ?olabel] 
  [(optional [[?s ?p ?o]]
                   [[?o :label ?olabel]]])
```

Which is equivalent to the following SPARQL:

```sparql
SELECT ?s ?p ?o ?olabel WHERE {
  { ?s ?p ?o } 
  OPTIONAL 
  { ?s ?p ?o . 
     ?o rdfs:label ?olabel .
  }
}
```

Which would then simply need to compile into this core.logic program:

```clojure
(pldb/with-db
    db
    (l/run*
      [?s ?p ?o ?olabel]
      (l/fresh
        []
        (l/conde
          [(triple ?s ?p ?o)]
          [(triple ?s ?p ?o)
           (triple ?o :label ?olabel)]))))
```
If you define a db

```clojure
(def db (index-triples [[:s :p :o1] [:o1 :label "label"] [:s2 :p :o2]]))
```

and evaluate the above you'll then get:

```clojure
;; => ([:o1 :label "label" _0] [:s :p :o1 _0] [:s :p :o1 "label"] [:s2 :p :o2 _0])
```

Which probably brings us to a decision we need to make...  Which is what to do with the `_N` markers.  The `_0`'s are core.logic's representation of the unbound variable `?olabel`.  Matcha will currently emit these if you don't project a variable, e.g. you'll see it if you run the query `(select [?s ?p ?o] [[:s ?p ?o]])` In a db containing `:s`, but you'll see them much more often when we introduce the `conde`.

We can either drop them completely e.g. return

```
;; => ([:o1 :label "label"] [:s :p :o1] [:s :p :o1 "label"] [:s2 :p :o2])
```

Or replace them with `nil` e.g.

```
;; => ([:o1 :label "label" nil] [:s :p :o1 nil] [:s :p :o1 "label"] [:s2 :p :o2 nil])
```

I think we may want to convert them to `nil`, as consider the `construct`:

```clojure
(construct {?olabel ?s} 
  (optional [[?s ?p ?o]]
                   [[?o :label ?olabel]])
```

Which semantically seems to imply a map like this: `{:s}`, which is invalid.  In reality clearly we'd just not create the key there, but it seems that coercing to `nil` might have more obvious behaviour.

Additionally I think `optional` should be variadic i.e. each form just maps to a `conde` expression.

The biggest difficulty in doing this will most likely be teaching `select` et al to expect `(optional ,,,)` forms as well as BGPs and to handle them correctly during the expansion.
